### PR TITLE
refactor(protocol): change *http.Request parameter

### PR DESCRIPTION
**Pull request by rgcruz010**
This is a breaking API change, but I don't see it necessary to pass the entire request to the library. The responsibility lies only in processing the body bytes, parsing them, and performing the corresponding validations related to the protocol.

All boilerplate code like:

```go

bytes, err := io.ReadAll(request.Body)
if err != nil {
    return err
}

defer request.Body.Close()
```

it's better off be part of the handler layer

### CODE REVIEW

**Comment by james-d-elliott** [comment]
As it is a breaking change as you've already identified; and it's actually a sizable breaking change, and the effective functionality can be implemented without a breaking change it would require a sizable benefit over not doing it for me to accept this I think. I don't currently see it that way.

Maybe you'd be interested in explaining that or in adjusting this potential enhancement to be backwards compatible via leaving the existing methods intact and refactoring them to use bytes methods. This would also add flexibility to the implementer.

**Comment by rgcruz010** [comment]
Thanks for the answer, it is more of a design decision so that the library has a simpler and more limited responsibility than handling the complete HTTP request. I will make another proposal as you suggest, seeing the possibility of backward compatibility.

**Comment by james-d-elliott** [comment]
Checkout #258 which should satisfy all of the elements in this PR with the exclusion of changing the Finish* functions, which effectively just parse the data and execute an exported method from the WebAuthn struct.

**Comment by rgcruz010** [comment]
This way #258 is better!

**Pull request closed without merging**
