### PR TITLE
feat: add config option to add multiple rp origins

### PR DESCRIPTION
**Pull request by FreddyDevelop**
Hi, I implemented a simple solution that solves #76

### CODE REVIEW

**Comment by james-d-elliott** [comment]
Hey Freddy! Looking great so far. Thanks for contributing. 

I'm thinking we could restore the original string field, mark it as deprecated, and ensure it makes it into the slice. It'll give users a grace period to resolve this. While we're likely to make breaking changes before v1, where possible it's nice to make the experience reasonably stable.

You may have already thought of this though and may have some thoughts on it?

**Comment by FreddyDevelop** [comment]
Yes, thats a good idea. I will add the original field back.

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Comment by james-d-elliott** [comment]
I'll take a closer look at some other libraries and merge it, but I'm 99% sure this is the correct method to handle this.

**Review by james-d-elliott — APPROVED** [review]

**Review by james-d-elliott — APPROVED** [review]

**Pull request merged**
